name: Run Robot Framework Tests

on: [push, pull_request]

jobs:
  e2e-tests:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Install Chocolatey
      run: |
        # Instalar Chocolatey
        iex "& { $(irm https://chocolatey.org/install.ps1 -UseBasicP) }"

    - name: Install JRE 8u421
      run: |
        # Instalar JRE 8u421 usando Chocolatey
        choco install jre8 --version 8.0.421 -y

    - name: Install Firebird 2.5
      run: |
        # Instalar Firebird 2.5 usando Chocolatey (se disponível)
        choco install firebirdsql --version 2.5 -y

    - name: Copy WinAppDriver to Program Files
      run: |
        # Criar o diretório se não existir
        if (-not (Test-Path "C:\Program Files (x86)\Windows Application Driver")) {
          New-Item -ItemType Directory -Path "C:\Program Files (x86)\Windows Application Driver"
        }

        # Copiar o WinAppDriver.exe para o diretório de destino
        Copy-Item -Path ".\WinAppDriver.exe" -Destination "C:\Program Files (x86)\Windows Application Driver\WinAppDriver.exe"

    - name: Start WinAppDriver
      run: |
        # Iniciar o WinAppDriver
        Start-Process "C:\Program Files (x86)\Windows Application Driver\WinAppDriver.exe"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install robotframework
        pip install robotframework-databaselibrary
        pip install robotframework-appiumlibrary
        pip install robotframework-SikuliLibrary
        pip install robotframework-ApplicationLibrary
        pip install firebirdsql
        pip install psutil

    - name: Run Robot Framework Tests
      run: |
        robot --outputdir results .\tests
        

    - name: Upload Test Results
      uses: actions/upload-artifact@v3
      with:
        name: robot-test-results
        path: results/
