name: Run Robot Framework Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Install Java 64-bit
      run: |
        # Baixar o instalador do Java 64-bit
        Invoke-WebRequest -Uri "https://download.java.com/java/GA/jdk20/8d0a5e0d1b8e4d9c9e0a6f6b8f637fc1/6c14c07a3a184d7d9f25e6c83757395b/jdk-20_windows-x64_bin.exe" -OutFile "jdk-20-windows-x64_bin.exe"
        
        # Executar o instalador
        Start-Process -FilePath "jdk-20-windows-x64_bin.exe" -ArgumentList "/s" -Wait

        # Configurar JAVA_HOME e PATH
        [Environment]::SetEnvironmentVariable("JAVA_HOME", "C:\Program Files\Java\jdk-20", [System.EnvironmentVariableTarget]::Machine)
        [Environment]::SetEnvironmentVariable("Path", "$env:Path;C:\Program Files\Java\jdk-20\bin", [System.EnvironmentVariableTarget]::Machine)

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install robotframework
        pip install DatabaseLibrary
        pip install ApplicationLibrary
        pip install SikuliLibrary
        # Instale o SikuliX se necessário; o SikuliLibrary pode precisar de uma instalação adicional de Java e SikuliX.
        # Você pode usar uma abordagem como baixar o SikuliX e configurá-lo manualmente.

    - name: Run Robot Framework Tests
      run: |
        robot --outputdir results .\tests
        # Certifique-se de que o diretório "tests" contém seus arquivos de teste.

    - name: Upload Test Results
      uses: actions/upload-artifact@v3
      with:
        name: robot-test-results
        path: results/
