name: Run Robot Framework Tests

on: [push, pull_request]

jobs:
  e2e-tests:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Install Chocolatey
      run: |
        # Instalar Chocolatey
        iex "& { $(irm https://chocolatey.org/install.ps1 -UseBasicP) }"

    - name: Install JRE 8u421
      run: |
        # Instalar JRE 8u421 usando Chocolatey
        choco install jre8 --version 8.0.421 -y

    - name: Download Firebird 2.5
      run: |
        # Baixar o instalador do Firebird 2.5
        Invoke-WebRequest -Uri "https://sourceforge.net/projects/firebird/files/firebird-win32/2.5.5-Release/Firebird-2.5.5.26952_0_Win32.exe" -OutFile "Firebird-2.5.5.26952_0_Win32.exe"
    
    - name: Verify Firebird Download
      run: |
        # Verificar se o arquivo foi baixado e seu tamanho
        if (-Not (Test-Path "Firebird-2.5.5.26952_0_Win32.exe")) {
          Write-Error "O arquivo Firebird-2.5.5.26952_0_Win32.exe não foi baixado."
          exit 1
        }
        
        $expectedSize = 24800000  # Substitua pelo tamanho esperado do arquivo em bytes
        $actualSize = (Get-Item "Firebird-2.5.5.26952_0_Win32.exe").Length
        
        if ($actualSize -lt $expectedSize) {
          Write-Error "O tamanho do arquivo baixado é menor do que o esperado."
          exit 1
        }    

    - name: Install Firebird 2.5
      run: |
        # Instalar Firebird 2.5
        Start-Process -FilePath ".\Firebird-2.5.5.26952_0_Win32.exe" -ArgumentList "/SILENT" -NoNewWindow -Wait

    - name: Verify Firebird Installation
      run: |
        # Verificar se o Firebird foi instalado corretamente
        & "C:\Program Files\Firebird\Firebird_2_5\bin\isql.exe" -?  # Comando para verificar a instalação

    # - name: Install Firebird 2.5
    #   run: |
    #     # Definir o caminho do arquivo
    #     $filePath = "$env:System_DefaultWorkingDirectory\Firebird-2.5.4.26856_0_Win32.exe"
    #     $tempDir = [System.IO.Path]::GetTempPath()
    #     $tempFilePath = [System.IO.Path]::Combine($tempDir, "Firebird-2.5.4.26856_0_Win32.exe")

    #     # Baixar o instalador do Firebird 2.5
    #     Invoke-WebRequest -Uri "https://sourceforge.net/projects/firebird/files/firebird-win32/2.5.5-Release/Firebird-2.5.5.26952_0_Win32.exe" -OutFile $filePath

    #     # Verificar se o arquivo foi baixado corretamente
    #     if (Test-Path $filePath) {
    #       # Copiar o arquivo para o diretório temporário
    #       Copy-Item -Path $filePath -Destination $tempFilePath

    #       # Executar o instalador silenciosamente a partir do diretório temporário
    #       Start-Process -FilePath $tempFilePath -ArgumentList "/SILENT" -Wait
    #     } else {
    #       Write-Error "O download do instalador do Firebird falhou."
    #     }

    - name: Copy WinAppDriver to Program Files
      run: |
        # Criar o diretório se não existir
        if (-not (Test-Path "C:\Program Files (x86)\Windows Application Driver")) {
          New-Item -ItemType Directory -Path "C:\Program Files (x86)\Windows Application Driver"
        }

        # Copiar o WinAppDriver.exe para o diretório de destino
        Copy-Item -Path ".\WinAppDriver.exe" -Destination "C:\Program Files (x86)\Windows Application Driver\WinAppDriver.exe"

    - name: Start WinAppDriver
      run: |
        # Iniciar o WinAppDriver
        Start-Process "C:\Program Files (x86)\Windows Application Driver\WinAppDriver.exe" -ArgumentList "/background"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install robotframework
        pip install robotframework-databaselibrary
        pip install robotframework-appiumlibrary
        pip install robotframework-SikuliLibrary
        pip install robotframework-ApplicationLibrary
        pip install firebirdsql
        pip install psutil

    - name: Run Robot Framework Tests
      run: |
        robot --outputdir results .\tests

    - name: Upload Test Results
      uses: actions/upload-artifact@v3
      with:
        name: robot-test-results
        path: results/
