name: Run Robot Framework Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Install Chocolatey
      run: |
        # Instalar Chocolatey
        iex "& { $(irm https://chocolatey.org/install.ps1 -UseBasicP) }"

    - name: Install JRE 8u421
      run: |
        # Instalar JRE 8u421 usando Chocolatey
        choco install jre8 --version 8.0.421 -y

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install robotframework
        pip install robotframework-databaselibrary
        pip install robotframework-appiumlibrary
        pip install robotframework-applicationlibrary
        pip install robotframework-SikuliLibrary
        # Instale o SikuliX se necessário; o SikuliLibrary pode precisar de uma instalação adicional de Java e SikuliX.
        # Você pode usar uma abordagem como baixar o SikuliX e configurá-lo manualmente.

    - name: Run Robot Framework Tests
      run: |
        robot --outputdir results .\tests
        # Certifique-se de que o diretório "tests" contém seus arquivos de teste.

    - name: Upload Test Results
      uses: actions/upload-artifact@v3
      with:
        name: robot-test-results
        path: results/
